### ISSUE TITLE
AttributeError exception on ClusteringModel

### ISSUE THREAD

**Issue by mguillau** [wvangansbeke/Unsupervised-Classification#3]
https://github.com/wvangansbeke/Unsupervised-Classification/blob/498aeae1528d0e9bcaa54a91bf16bc2b971150e9/scan.py#L111

This line was causing the following AttributeError exception for me:

```
Evaluate based on SCAN loss ...
{'scan': [{'entropy': 5.282749176025391, 'consistency': 5.058314800262451, 'total_loss': -0.22443437576293945}, {'entropy': 5.275367736816406, 'consistency': 5.054675579071045, 'total_loss': -0.22069215774536133}, {'entropy'
: 5.274453163146973, 'consistency': 5.050076007843018, 'total_loss': -0.22437715530395508}, {'entropy': 5.277739524841309, 'consistency': 5.065070152282715, 'total_loss': -0.21266937255859375}, {'entropy': 5.24068021774292, 
'consistency': 4.836734294891357, 'total_loss': -0.4039459228515625}, {'entropy': 5.279136657714844, 'consistency': 5.064798355102539, 'total_loss': -0.2143383026123047}, {'entropy': 5.278388500213623, 'consistency': 5.06134
5100402832, 'total_loss': -0.21704339981079102}, {'entropy': 5.279128074645996, 'consistency': 5.065242767333984, 'total_loss': -0.21388530731201172}, {'entropy': 5.277782440185547, 'consistency': 5.065756320953369, 'total_l
oss': -0.21202611923217773}, {'entropy': 5.276066303253174, 'consistency': 5.05104923248291, 'total_loss': -0.22501707077026367}], 'lowest_loss_head': 4, 'lowest_loss': -0.4039459228515625}
New lowest loss on validation set: 10000.0000 -> -0.4039
Lowest loss head is 4
Traceback (most recent call last):
  File "scan.py", line 139, in <module>
    main()
  File "scan.py", line 111, in main
    torch.save({'model': model.module.state_dict(), 'head': best_loss_head}, p['scan_model'])
  File "/home/ubuntu/anaconda3/envs/Unsupervised-Classification/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'ClusteringModel' object has no attribute 'module'
```

Removing `.module` seems to fix the issue.

**Comment by wvangansbeke** [comment]
Ok I will fix it.

**Comment by wvangansbeke** [comment]
I wrapped the model with nn.Dataparallel. Should be fixed now.
