### ISSUE TITLE
Getting error while running scan.py at dataloader.

### ISSUE THREAD

**Issue by sato-takahashi** [wvangansbeke/Unsupervised-Classification#75]
Hi, thanks for your excellent work.

I am training with my own dataset.
I succeed with 34 crop size, however, I faild with 64 crop size at "scan.py".
My dataset has 14 classes and I used resnet50 and 64 crop size at simclr's yml and scan's yml.
The shpes of all image are lager than 64 x 64.
I set num_neighbors as 5, 20 and 100, however, I failed at all cases.
I assume that the num_neighbors is not appropriate.
Could you give me some advice?

The result of "simclr.py" is below.

Adjusted learning rate to 0.00040
Train ...
Epoch: [499][ 0/20]	Loss 1.3336e+00 (1.3336e+00)
Fill memory bank for kNN...
Fill Memory Bank [0/21]
Evaluate ...
Result of kNN evaluation is 32.28
Checkpoint ...
[34mFill memory bank for mining the nearest neighbors (train) ...[0m
Fill Memory Bank [0/21]
Mine the nearest neighbors (Top-20)
Accuracy of top-20 nearest neighbors on train set is 19.04
[34mFill memory bank for mining the nearest neighbors (val) ...[0m
Fill Memory Bank [0/6]
Mine the nearest neighbors (Top-5)
Accuracy of top-5 nearest neighbors on val set is 17.95

The result of "scan.py" is below.

Adjusted learning rate to 0.00010
Train ...
Epoch: [0][ 0/82]	Total Loss -1.0549e+01 (-1.0549e+01)	Consistency Loss 2.6344e+00 (2.6344e+00)	Entropy 2.6367e+00 (2.6367e+00)
Epoch: [0][25/82]	Total Loss -1.0558e+01 (-1.0561e+01)	Consistency Loss 2.6336e+00 (2.6329e+00)	Entropy 2.6383e+00 (2.6387e+00)
Traceback (most recent call last):
  File "scan.py", line 140, in <module>
    main()
  File "scan.py", line 95, in main
    scan_train(train_dataloader, model, criterion, optimizer, epoch, p['update_cluster_head_only'])
  File "/home/w49084a/working/20210716/test/utils/train_utils.py", line 59, in scan_train
    for i, batch in enumerate(train_loader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/w49084a/working/20210716/test/data/custom_dataset.py", line 74, in __getitem__
    anchor['image'] = self.anchor_transform(anchor['image'])
  File "/opt/conda/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 483, in __call__
    i, j, h, w = self.get_params(img, self.size)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 462, in get_params
    j = random.randint(0, w - tw)
  File "/opt/conda/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/opt/conda/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-2, -2)

**Comment by wvangansbeke** [comment]
Hi @sato-takahashi,

Thank you for your interest.
My guess is that your input resolution is not constant. This can cause the randomcrop augmentation to go out of range. You can try resizing the image first before cropping or try using a smaller crop size.

**Comment by sato-takahashi** [comment]
Thank you for your quick reply!
I will try that.

**Comment by wvangansbeke** [comment]
I hope you figured it out. If you have any questions, let us know. Closing this for now.
