### ISSUE TITLE
AttributeError: 'ClusteringModel' object has no attribute 'module'

### ISSUE THREAD

**Issue by heesubsong** [wvangansbeke/Unsupervised-Classification#9]
Hello

An error occurred while trying to run the test code.

The data sets were cifar10 and cifar20.

The simclr.py code works fine, but the scan.py code does not.

What is the problem?

'''
Make prediction on validation set ...
Evaluate based on SCAN loss ...
{'scan': [{'entropy': 2.980037212371826, 'consistency': 2.5082473754882812, 'total_loss': -0.4717898368835449}], 'lowest_loss_head': 0, 'lowest_loss': -0.4717898368835449}
New lowest loss on validation set: 10000.0000 -> -0.4718
Lowest loss head is 0
Traceback (most recent call last):
  File "scan.py", line 139, in <module>
    main()
  File "scan.py", line 111, in main
    torch.save({'model': model.module.state_dict(), 'head': best_loss_head}, p['scan_model'])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'ClusteringModel' object has no attribute 'module'
'''

**Comment by heesubsong** [comment]
It works fine after receiving a new git pull today.

Thank you.
